# プレフィックスを Ctrl + a に変更
unbind C-b
set-option -g prefix C-t
bind C-t send-prefix
bind-key X kill-server

# 履歴に保持する最大行数を設定（デフォルトは2000行）
set-option -g history-limit 25000

# マウス操作を有効化（ペイン分割やスクロールにマウスを使用可能）
set -g mouse on

# Neovim 用の設定
# Esc キーの遅延時間を10msに設定（モード切替をスムーズに）
set -sg escape-time 10
# ペインやウィンドウのフォーカスイベントを Neovim に通知
set-option -g focus-events on

# コピーモードでのキー操作を vi スタイルに変更
#setw -g mode-keys vi

# ステータスバーの設定（ペイン名を中央に表示）
set -g status-justify centre          # ステータスバーを中央揃えに設定
set -g status-left ""                 # ステータスバー左側を空に設定
set -g status-right ""                # ステータスバー右側を空に設定
set -g status-position top
set -g status-style "bg=default,fg=#665c54"  # ステータスバー全体のスタイル設定
set -g window-status-format " #[fg=#665c54]#I:#W "  # ペインのフォーマット設定
set -g window-status-current-format "#[fg=#928374,bold]#I:#W"  # 現在のペインを強調

# ステータスバー左側に tmux または wait を表示
set -g status-left-length 20
set -g status-left "#[fg=#928374]#{?client_prefix,wait,tmux} "

# ステータスバー右側に現在の時刻を表示（YYYY MM DD）
set -g status-right-length 40              # 右側の最大幅を設定
set -g status-right "%H:%M:%S %d-%b"


# ペイン名を自動的に作業ディレクトリ名にリネーム
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# ステータスバーのオン・オフ（必要に応じてコメントを外す）
# set -g status off  # ステータスバーを無効化
# set -g status on   # ステータスバーを有効化

# ウィンドウとペインの番号を1から始める（デフォルトは0）
set -g base-index 1
setw -g pane-base-index 1

# 設定ファイルのリロード（Ctrl-b を押した後に r を押す）
bind-key -r r source-file ~/.tmux.conf

# ターミナルのカラーモードを設定（256色とRGB対応）
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'
set -g default-terminal "screen-256color"

